# Generated by Django 2.0.2 on 2019-11-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='comproagro', verbose_name='Imagen')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='comproagro', verbose_name='Imagen')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='comproagro', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.CharField(max_length=40, verbose_name='Correo')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created'],
            },
        ),
    ]
