# Generated by Django 2.0.2 on 2019-11-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comproagro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technic_field',
            field=models.FileField(blank=True, null=True, upload_to='comproagro/fichatecnica', verbose_name='Ficha Tecnica'),
        ),
    ]
